### ISSUE TITLE
Fails to deploy: Failed to create function

### ISSUE THREAD

**Issue by rsivan** [firebase/firebase-functions#1164]
### [REQUIRED] Version info

**node:**

v14.18.3
**firebase-functions:**
3.22.0
**firebase-tools:**

11.2.0
**firebase-admin:**
11.0.0
### [REQUIRED] Test case

Follow the initial samples of the official firebase functions documentation, which includes a helloWorld function
### [REQUIRED] Steps to reproduce

Follow the initial samples of the official firebase functions documentation, which includes a helloWorld function

### [REQUIRED] Expected behavior

Should deploy OK
### [REQUIRED] Actual behavior
Fails to deploy

[debug] [2022-07-05T18:55:14.552Z] ----------------------------------------------------------------------
[debug] [2022-07-05T18:55:14.553Z] Command:       /Users/rsivan/.nvm/versions/node/v14.18.3/bin/node /Users/rsivan/.nvm/versions/node/v14.18.3/bin/firebase deploy --debug
[debug] [2022-07-05T18:55:14.553Z] CLI Version:   11.2.0
[debug] [2022-07-05T18:55:14.553Z] Platform:      darwin
[debug] [2022-07-05T18:55:14.553Z] Node Version:  v14.18.3
[debug] [2022-07-05T18:55:14.557Z] Time:          Tue Jul 05 2022 11:55:14 GMT-0700 (Pacific Daylight Time)
[debug] [2022-07-05T18:55:14.558Z] ----------------------------------------------------------------------
[debug] 
[debug] [2022-07-05T18:55:14.610Z] > command requires scopes: ["email","openid","https://www.googleapis.com/auth/cloudplatformprojects.readonly","https://www.googleapis.com/auth/firebase","https://www.googleapis.com/auth/cloud-platform"]
[debug] [2022-07-05T18:55:14.610Z] > authorizing via signed-in user (rsivan@sivansoftware.com)
[debug] [2022-07-05T18:55:14.611Z] [iam] checking project actus22-92c20 for permissions ["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]
[debug] [2022-07-05T18:55:14.613Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions [none]
[debug] [2022-07-05T18:55:14.613Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2022-07-05T18:55:15.110Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions 200
[debug] [2022-07-05T18:55:15.111Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions {"permissions":["cloudfunctions.functions.create","cloudfunctions.functions.delete","cloudfunctions.functions.get","cloudfunctions.functions.list","cloudfunctions.functions.update","cloudfunctions.operations.get","firebase.projects.get","firebasehosting.sites.update"]}
[debug] [2022-07-05T18:55:15.112Z] >>> [apiv2][query] POST https://iam.googleapis.com/v1/projects/actus22-92c20/serviceAccounts/actus22-92c20@appspot.gserviceaccount.com:testIamPermissions [none]
[debug] [2022-07-05T18:55:15.112Z] >>> [apiv2][body] POST https://iam.googleapis.com/v1/projects/actus22-92c20/serviceAccounts/actus22-92c20@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2022-07-05T18:55:15.462Z] <<< [apiv2][status] POST https://iam.googleapis.com/v1/projects/actus22-92c20/serviceAccounts/actus22-92c20@appspot.gserviceaccount.com:testIamPermissions 200
[debug] [2022-07-05T18:55:15.462Z] <<< [apiv2][body] POST https://iam.googleapis.com/v1/projects/actus22-92c20/serviceAccounts/actus22-92c20@appspot.gserviceaccount.com:testIamPermissions {"permissions":["iam.serviceAccounts.actAs"]}
[debug] [2022-07-05T18:55:15.463Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 [none]
[debug] [2022-07-05T18:55:15.831Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 200
[debug] [2022-07-05T18:55:15.831Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 {"projectId":"actus22-92c20","projectNumber":"400622102138","displayName":"actus22","name":"projects/actus22-92c20","resources":{"hostingSite":"actus22-92c20","storageBucket":"actus22-92c20.appspot.com","locationId":"us-west1"},"state":"ACTIVE"}
[info] 
[info] === Deploying to 'actus22-92c20'...
[info] 
[info] i  deploying functions, hosting 
[info] Running command: npm --prefix "$RESOURCE_DIR" run lint
[info] Running command: npm --prefix "$RESOURCE_DIR" run build
[info] ✔  functions: Finished running predeploy script. 
[debug] [2022-07-05T18:55:29.133Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 [none]
[debug] [2022-07-05T18:55:29.363Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 200
[debug] [2022-07-05T18:55:29.363Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 {"projectId":"actus22-92c20","projectNumber":"400622102138","displayName":"actus22","name":"projects/actus22-92c20","resources":{"hostingSite":"actus22-92c20","storageBucket":"actus22-92c20.appspot.com","locationId":"us-west1"},"state":"ACTIVE"}
[info] i  functions: ensuring required API cloudfunctions.googleapis.com is enabled... 
[info] i  functions: ensuring required API cloudbuild.googleapis.com is enabled... 
[debug] [2022-07-05T18:55:29.367Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/cloudfunctions.googleapis.com [none]
[debug] [2022-07-05T18:55:29.373Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/runtimeconfig.googleapis.com [none]
[debug] [2022-07-05T18:55:29.375Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/cloudbuild.googleapis.com [none]
[debug] [2022-07-05T18:55:29.376Z] >>> [apiv2][query] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/artifactregistry.googleapis.com [none]
[debug] [2022-07-05T18:55:29.820Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/runtimeconfig.googleapis.com 200
[debug] [2022-07-05T18:55:29.820Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/runtimeconfig.googleapis.com [omitted]
[debug] [2022-07-05T18:55:29.823Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/artifactregistry.googleapis.com 200
[debug] [2022-07-05T18:55:29.823Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/artifactregistry.googleapis.com [omitted]
[debug] [2022-07-05T18:55:29.826Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/cloudfunctions.googleapis.com 200
[debug] [2022-07-05T18:55:29.826Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/cloudfunctions.googleapis.com [omitted]
[info] ✔  functions: required API cloudfunctions.googleapis.com is enabled 
[debug] [2022-07-05T18:55:29.829Z] <<< [apiv2][status] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/cloudbuild.googleapis.com 200
[debug] [2022-07-05T18:55:29.830Z] <<< [apiv2][body] GET https://serviceusage.googleapis.com/v1/projects/actus22-92c20/services/cloudbuild.googleapis.com [omitted]
[info] ✔  functions: required API cloudbuild.googleapis.com is enabled 
[debug] [2022-07-05T18:55:29.830Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20/adminSdkConfig [none]
[debug] [2022-07-05T18:55:30.076Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20/adminSdkConfig 200
[debug] [2022-07-05T18:55:30.076Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20/adminSdkConfig {"projectId":"actus22-92c20","storageBucket":"actus22-92c20.appspot.com","locationId":"us-west1"}
[debug] [2022-07-05T18:55:30.078Z] >>> [apiv2][query] GET https://runtimeconfig.googleapis.com/v1beta1/projects/actus22-92c20/configs [none]
[debug] [2022-07-05T18:55:30.426Z] <<< [apiv2][status] GET https://runtimeconfig.googleapis.com/v1beta1/projects/actus22-92c20/configs 200
[debug] [2022-07-05T18:55:30.427Z] <<< [apiv2][body] GET https://runtimeconfig.googleapis.com/v1beta1/projects/actus22-92c20/configs {}
[info] i  functions: preparing codebase default for deployment 
[debug] [2022-07-05T18:55:30.428Z] Validating nodejs source
[debug] [2022-07-05T18:55:31.546Z] > [functions] package.json contents: {
  "name": "functions",
  "scripts": {
    "lint": "eslint --ext .js,.ts .",
    "build": "tsc",
    "build:watch": "tsc --watch",
    "serve": "npm run build && firebase emulators:start --only functions",
    "shell": "npm run build && firebase functions:shell",
    "start": "npm run shell",
    "deploy": "firebase deploy --only functions --debug",
    "logs": "firebase functions:log"
  },
  "engines": {
    "node": "16"
  },
  "main": "lib/index.js",
  "dependencies": {
    "firebase-admin": "^10.0.2",
    "firebase-functions": "^3.18.0"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^5.12.0",
    "@typescript-eslint/parser": "^5.12.0",
    "eslint": "^8.9.0",
    "eslint-config-google": "^0.14.0",
    "eslint-plugin-import": "^2.25.4",
    "firebase-functions-test": "^0.2.0",
    "typescript": "^4.5.4"
  },
  "private": true
}
[debug] [2022-07-05T18:55:31.546Z] Building nodejs source
[debug] [2022-07-05T18:55:31.548Z] Could not find functions.yaml. Must use http discovery
[debug] [2022-07-05T18:55:31.697Z] Serving at port 9005

[debug] [2022-07-05T18:55:31.745Z] Got response from /__/functions.yaml {"endpoints":{"helloWorld":{"platform":"gcfv1","httpsTrigger":{},"entryPoint":"helloWorld"}},"specVersion":"v1alpha1","requiredAPIs":[]}
[debug] [2022-07-05T18:55:31.751Z] shutdown requested via /__/quitquitquit

[info] i  functions: preparing functions directory for uploading... 
[info] i  functions: packaged /Users/rsivan/GitHub/video1/functions (94.2 KB) for uploading 
[debug] [2022-07-05T18:55:31.811Z] >>> [apiv2][query] GET https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/-/functions [none]
[debug] [2022-07-05T18:55:32.417Z] <<< [apiv2][status] GET https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/-/functions 200
[debug] [2022-07-05T18:55:32.418Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/-/functions {}
[debug] [2022-07-05T18:55:32.419Z] >>> [apiv2][query] GET https://cloudfunctions.googleapis.com/v2alpha/projects/actus22-92c20/locations/-/functions [none]
[debug] [2022-07-05T18:55:33.238Z] <<< [apiv2][status] GET https://cloudfunctions.googleapis.com/v2alpha/projects/actus22-92c20/locations/-/functions 200
[debug] [2022-07-05T18:55:33.238Z] <<< [apiv2][body] GET https://cloudfunctions.googleapis.com/v2alpha/projects/actus22-92c20/locations/-/functions {}
[debug] [2022-07-05T18:55:33.249Z] >>> [apiv2][query] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 [none]
[debug] [2022-07-05T18:55:33.618Z] <<< [apiv2][status] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 200
[debug] [2022-07-05T18:55:33.618Z] <<< [apiv2][body] GET https://firebase.googleapis.com/v1beta1/projects/actus22-92c20 {"projectId":"actus22-92c20","projectNumber":"400622102138","displayName":"actus22","name":"projects/actus22-92c20","resources":{"hostingSite":"actus22-92c20","storageBucket":"actus22-92c20.appspot.com","locationId":"us-west1"},"state":"ACTIVE"}
[debug] [2022-07-05T18:55:33.623Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions [none]
[debug] [2022-07-05T18:55:33.624Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions {"config":{"rewrites":[{"glob":"**","path":"/index.html"}]},"labels":{"deployment-tool":"cli-firebase"}}
[debug] [2022-07-05T18:55:34.352Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions 200
[debug] [2022-07-05T18:55:34.352Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions {"name":"projects/400622102138/sites/actus22-92c20/versions/c1a8fafcd7a53cd0","status":"CREATED","config":{"rewrites":[{"glob":"**","path":"/index.html"}]},"labels":{"deployment-tool":"cli-firebase"}}
[debug] [2022-07-05T18:55:34.354Z] [functions] found 1 new HTTP functions, testing setIamPolicy permission...
[debug] [2022-07-05T18:55:34.355Z] >>> [apiv2][query] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions [none]
[debug] [2022-07-05T18:55:34.355Z] >>> [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions {"permissions":["cloudfunctions.functions.setIamPolicy"]}
[debug] [2022-07-05T18:55:34.614Z] <<< [apiv2][status] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions 200
[debug] [2022-07-05T18:55:34.614Z] <<< [apiv2][body] POST https://cloudresourcemanager.googleapis.com/v1/projects/actus22-92c20:testIamPermissions {"permissions":["cloudfunctions.functions.setIamPolicy"]}
[debug] [2022-07-05T18:55:34.614Z] [functions] found setIamPolicy permission, proceeding with deploy
[debug] [2022-07-05T18:55:34.616Z] >>> [apiv2][query] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions:generateUploadUrl [none]
[debug] [2022-07-05T18:55:34.616Z] >>> [apiv2][body] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions:generateUploadUrl {}
[debug] [2022-07-05T18:55:35.378Z] <<< [apiv2][status] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions:generateUploadUrl 200
[debug] [2022-07-05T18:55:35.379Z] <<< [apiv2][body] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions:generateUploadUrl {"uploadUrl":"https://storage.googleapis.com/uploads-313999636888.us-central1.cloudfunctions.appspot.com/6d978e1b-d21f-49ef-b4bb-5cd34758bf15.zip?GoogleAccessId=service-400622102138@gcf-admin-robot.iam.gserviceaccount.com&Expires=1657049135&Signature=Qon7f8Is1eNF0%2Fu0SL8REPRM%2FbcnKq8nIJpD242rYHRfP0AlOtRbaMnPwXSouE1VIqzQ5SM%2BOxLQrNh%2BP4InW7Qgy1k%2Fq5qY%2B%2F7diEdVbPbjP04NygT8eHNmp0RTfSVVqsciZQ1LjTH0RpMtQyxdZjHF1SWn80qHiK0T3S4c8KlHuV3Yb7Cq1%2FbZu7gyrsOqKu%2BoJzJwraLLfKcSJ7OmodKEO9lhZtFhENXPIhNFWhbteRX%2BCo53E34xvRAyrzvW%2B0tL%2FRkLI%2B8CvMdZHrrurl1eVHanFrY5NQ4cNohRQh%2FpypSJ938rV0YMgLm%2FRXNK22bJJGBrJFMvphel5Rk7CQ%3D%3D"}
[debug] [2022-07-05T18:55:35.381Z] >>> [apiv2][query] PUT https://storage.googleapis.com/uploads-313999636888.us-central1.cloudfunctions.appspot.com/6d978e1b-d21f-49ef-b4bb-5cd34758bf15.zip GoogleAccessId=service-400622102138%40gcf-admin-robot.iam.gserviceaccount.com&Expires=1657049135&Signature=Qon7f8Is1eNF0%2Fu0SL8REPRM%2FbcnKq8nIJpD242rYHRfP0AlOtRbaMnPwXSouE1VIqzQ5SM%2BOxLQrNh%2BP4InW7Qgy1k%2Fq5qY%2B%2F7diEdVbPbjP04NygT8eHNmp0RTfSVVqsciZQ1LjTH0RpMtQyxdZjHF1SWn80qHiK0T3S4c8KlHuV3Yb7Cq1%2FbZu7gyrsOqKu%2BoJzJwraLLfKcSJ7OmodKEO9lhZtFhENXPIhNFWhbteRX%2BCo53E34xvRAyrzvW%2B0tL%2FRkLI%2B8CvMdZHrrurl1eVHanFrY5NQ4cNohRQh%2FpypSJ938rV0YMgLm%2FRXNK22bJJGBrJFMvphel5Rk7CQ%3D%3D
[debug] [2022-07-05T18:55:35.381Z] >>> [apiv2][body] PUT https://storage.googleapis.com/uploads-313999636888.us-central1.cloudfunctions.appspot.com/6d978e1b-d21f-49ef-b4bb-5cd34758bf15.zip [stream]
[debug] [2022-07-05T18:55:35.783Z] <<< [apiv2][status] PUT https://storage.googleapis.com/uploads-313999636888.us-central1.cloudfunctions.appspot.com/6d978e1b-d21f-49ef-b4bb-5cd34758bf15.zip 200
[debug] [2022-07-05T18:55:35.784Z] <<< [apiv2][body] PUT https://storage.googleapis.com/uploads-313999636888.us-central1.cloudfunctions.appspot.com/6d978e1b-d21f-49ef-b4bb-5cd34758bf15.zip [omitted]
[info] ✔  functions: functions folder uploaded successfully 
[info] i  hosting[actus22-92c20]: beginning deploy... 
[info] i  hosting[actus22-92c20]: found 1 files in public 
[debug] [2022-07-05T18:55:35.795Z] [hosting] uploading with 200 concurrency
[debug] [2022-07-05T18:55:35.802Z] [hosting] hash cache [cHVibGlj] stored for 1 files
[debug] [2022-07-05T18:55:35.803Z] [hosting][hash queue][FINAL] {"max":1,"min":1,"avg":1,"active":0,"complete":1,"success":1,"errored":0,"retried":0,"total":1,"elapsed":4}
[debug] [2022-07-05T18:55:35.804Z] >>> [apiv2][query] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions/c1a8fafcd7a53cd0:populateFiles [none]
[debug] [2022-07-05T18:55:35.805Z] >>> [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions/c1a8fafcd7a53cd0:populateFiles {"files":{"/index.html":"aa80be975ba55477e7c5a02251827a49f0987830e6844af7524251304e361b6b"}}
[debug] [2022-07-05T18:55:36.504Z] <<< [apiv2][status] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions/c1a8fafcd7a53cd0:populateFiles 200
[debug] [2022-07-05T18:55:36.504Z] <<< [apiv2][body] POST https://firebasehosting.googleapis.com/v1beta1/projects/400622102138/sites/actus22-92c20/versions/c1a8fafcd7a53cd0:populateFiles {"uploadUrl":"https://upload-firebasehosting.googleapis.com/upload/sites/actus22-92c20/versions/c1a8fafcd7a53cd0/files"}
[debug] [2022-07-05T18:55:36.505Z] [hosting][populate queue][FINAL] {"max":705,"min":705,"avg":705,"active":0,"complete":1,"success":1,"errored":0,"retried":0,"total":1,"elapsed":705}
[debug] [2022-07-05T18:55:36.505Z] [hosting] uploads queued: 0
[debug] [2022-07-05T18:55:36.506Z] [hosting][upload queue][FINAL] {"max":0,"min":9999999999,"avg":0,"active":0,"complete":0,"success":0,"errored":0,"retried":0,"total":0,"elapsed":1657047336506}
[info] ✔  hosting[actus22-92c20]: file upload complete 
[debug] [2022-07-05T18:55:36.507Z] [hosting] deploy completed after 720ms
[info] i  functions: creating Node.js 16 function helloWorld(us-central1)... 
[debug] [2022-07-05T18:55:36.515Z] >>> [apiv2][query] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions [none]
[debug] [2022-07-05T18:55:36.515Z] >>> [apiv2][body] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions {"name":"projects/actus22-92c20/locations/us-central1/functions/helloWorld","sourceUploadUrl":"https://storage.googleapis.com/uploads-313999636888.us-central1.cloudfunctions.appspot.com/6d978e1b-d21f-49ef-b4bb-5cd34758bf15.zip?GoogleAccessId=service-400622102138@gcf-admin-robot.iam.gserviceaccount.com&Expires=1657049135&Signature=Qon7f8Is1eNF0%2Fu0SL8REPRM%2FbcnKq8nIJpD242rYHRfP0AlOtRbaMnPwXSouE1VIqzQ5SM%2BOxLQrNh%2BP4InW7Qgy1k%2Fq5qY%2B%2F7diEdVbPbjP04NygT8eHNmp0RTfSVVqsciZQ1LjTH0RpMtQyxdZjHF1SWn80qHiK0T3S4c8KlHuV3Yb7Cq1%2FbZu7gyrsOqKu%2BoJzJwraLLfKcSJ7OmodKEO9lhZtFhENXPIhNFWhbteRX%2BCo53E34xvRAyrzvW%2B0tL%2FRkLI%2B8CvMdZHrrurl1eVHanFrY5NQ4cNohRQh%2FpypSJ938rV0YMgLm%2FRXNK22bJJGBrJFMvphel5Rk7CQ%3D%3D","entryPoint":"helloWorld","runtime":"nodejs16","dockerRegistry":"ARTIFACT_REGISTRY","labels":{"deployment-tool":"cli-firebase"},"httpsTrigger":{"securityLevel":"SECURE_ALWAYS"},"environmentVariables":{"FIREBASE_CONFIG":"{\"projectId\":\"actus22-92c20\",\"storageBucket\":\"actus22-92c20.appspot.com\",\"locationId\":\"us-west1\"}","GCLOUD_PROJECT":"actus22-92c20"},"timeout":"60s"}
[debug] [2022-07-05T18:55:36.815Z] <<< [apiv2][status] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions 403
[debug] [2022-07-05T18:55:36.816Z] <<< [apiv2][body] POST https://cloudfunctions.googleapis.com/v1/projects/actus22-92c20/locations/us-central1/functions {"error":{"code":403,"message":"Cloud Functions uses Artifact Registry to store function docker images. Artifact Registry API is not enabled in your project. To enable the API, visit https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=400622102138 or use the gcloud command 'gcloud services enable artifactregistry.googleapis.com' then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED"}}
[warn] ⚠  functions: failed to create function projects/actus22-92c20/locations/us-central1/functions/helloWorld 
[error] Failed to create function projects/actus22-92c20/locations/us-central1/functions/helloWorld
[debug] [2022-07-05T18:55:36.826Z] Total Function Deployment time: 309
[debug] [2022-07-05T18:55:36.827Z] 1 Functions Deployed
[debug] [2022-07-05T18:55:36.827Z] 1 Functions Errored
[debug] [2022-07-05T18:55:36.827Z] 0 Function Deployments Aborted
[debug] [2022-07-05T18:55:36.827Z] Average Function Deployment time: 307
[info] 
[info] Functions deploy had errors with the following functions:
	helloWorld(us-central1)
[debug] [2022-07-05T18:55:37.075Z] Not printing URL for HTTPS function. Typically this means it didn't match a filter or we failed deployment
[info] i  functions: cleaning up build files... 
[debug] [2022-07-05T18:55:37.077Z] >>> [apiv2][query] DELETE https://artifactregistry.googleapis.com/v1beta2/projects/actus22-92c20/locations/us-central1/repositories/gcf-artifacts/packages/hello_world [none]
[debug] [2022-07-05T18:55:37.078Z] >>> [apiv2][query] GET https://us.gcr.io/v2/actus22-92c20/gcf/us-central1/tags/list [none]
[debug] [2022-07-05T18:55:37.258Z] <<< [apiv2][status] GET https://us.gcr.io/v2/actus22-92c20/gcf/us-central1/tags/list 200
[debug] [2022-07-05T18:55:37.258Z] <<< [apiv2][body] GET https://us.gcr.io/v2/actus22-92c20/gcf/us-central1/tags/list {"child":[],"manifest":{},"name":"actus22-92c20/gcf/us-central1","tags":[]}
[debug] [2022-07-05T18:55:37.259Z] Could not find image for function projects/actus22-92c20/locations/us-central1/functions/helloWorld
[debug] [2022-07-05T18:55:37.470Z] <<< [apiv2][status] DELETE https://artifactregistry.googleapis.com/v1beta2/projects/actus22-92c20/locations/us-central1/repositories/gcf-artifacts/packages/hello_world 403
[debug] [2022-07-05T18:55:37.470Z] <<< [apiv2][body] DELETE https://artifactregistry.googleapis.com/v1beta2/projects/actus22-92c20/locations/us-central1/repositories/gcf-artifacts/packages/hello_world {"error":{"code":403,"message":"Artifact Registry API has not been used in project 400622102138 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=400622102138 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=400622102138"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"artifactregistry.googleapis.com","consumer":"projects/400622102138"}}]}}
[warn] ⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/artifacts/docker/actus22-92c20/us-central1/gcf-artifacts 
[debug] [2022-07-05T18:55:37.583Z] Error: Failed to create function helloWorld in region us-central1
    at /Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:41:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Fabricator.createV1Function (/Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:167:32)
    at async Fabricator.createEndpoint (/Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:118:13)
    at async handle (/Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:77:17)
[error] 
[error] Error: There was an error deploying functions

### Were you able to successfully deploy your functions?

see above.
also see debug info:

[2022-07-05T18:55:37.470Z] <<< [apiv2][body] DELETE https://artifactregistry.googleapis.com/v1beta2/projects/actus22-92c20/locations/us-central1/repositories/gcf-artifacts/packages/hello_world {"error":{"code":403,"message":"Artifact Registry API has not been used in project 400622102138 before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=400622102138 then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry.","status":"PERMISSION_DENIED","details":[{"@type":"type.googleapis.com/google.rpc.Help","links":[{"description":"Google developers console API activation","url":"https://console.developers.google.com/apis/api/artifactregistry.googleapis.com/overview?project=400622102138"}]},{"@type":"type.googleapis.com/google.rpc.ErrorInfo","reason":"SERVICE_DISABLED","domain":"googleapis.com","metadata":{"service":"artifactregistry.googleapis.com","consumer":"projects/400622102138"}}]}}
⚠  functions: Unhandled error cleaning up build images. This could result in a small monthly bill if not corrected. You can attempt to delete these images by redeploying or you can delete them manually at https://console.cloud.google.com/artifacts/docker/actus22-92c20/us-central1/gcf-artifacts 
[2022-07-05T18:55:37.583Z] Error: Failed to create function helloWorld in region us-central1
    at /Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:41:11
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Fabricator.createV1Function (/Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:167:32)
    at async Fabricator.createEndpoint (/Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:118:13)
    at async handle (/Users/rsivan/.nvm/versions/node/v14.18.3/lib/node_modules/firebase-tools/lib/deploy/functions/release/fabricator.js:77:17)

Error: There was an error deploying functions

**Comment by GokupcWork** [comment]
Same error

**Comment by eridr** [comment]
Same Error

**Comment by tooooofu24** [comment]
Same error

**Comment by Guirdin** [comment]
Same error. I just followed the normal installation of a cloud function project. I find myself with
```Error: There was an error deploying functions``` on the example “helloWorld” function.

i functions: creating Node.js 16 function helloWorld(us-central1)...
! functions: failed to create function projects/my-app/locations/us-central1/functions/helloWorld
Failed to create function projects/my-app/locations/us-central1/functions/helloWorld

**Comment by tooooofu24** [comment]
I don't think it is the best solution, but downgrading `firebase-tools` solved the problem.
firebase-tools@11.2.0 doesn't work well now.
But firebase-tools@10.6.0 works well.
So if you want to deploy right now, try it.
```
npm install -g firebase-tools@10.6.0
```

**Comment by SamGostling** [comment]
> Cloud Functions uses Artifact Registry to store function docker images. Artifact Registry API is not enabled in your project

Not 100% sure, but I think it might be something to do with Google wanting people to transition from Container Registry to Artifact Registry for container image storage and management.  It looks like they are switching Firebase Cloud functions to using Artifact registry and this is where the issue is arising.

I came across this issue a couple of hours ago and fixed it by going into gcloud and enabling the Artifact Registry API.  I waited about 10 mins then tried to deploy my cloud functions again and all worked fine.

**Comment by taeold** [comment]
@SamGostling You are correct. Google Cloud Function is moving customers toward Artifact Registry, and we missed logic to enable AR on your project. This is now fixed in the latest version of the Firebase CLI 11.2.1

**Comment by JoDeveloper** [comment]
> Artifact Registry API.

Artifact Registry API is enabled in my project , but still cant upload my functions 
```
i  deploying functions
⚠  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.
⚠  functions: Please note that there will be breaking changes when you upgrade.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
✔  functions: required API artifactregistry.googleapis.com is enabled
✔  functions: required API cloudfunctions.googleapis.com is enabled
✔  functions: required API cloudbuild.googleapis.com is enabled
i  functions: preparing functions directory for uploading...
i  functions: packaged functions (58.77 KB) for uploading
✔  functions: functions folder uploaded successfully
i  functions: updating Node.js 16 function onVideoWrite(us-central1)...
i  functions: updating Node.js 16 function onChannelWrite(us-central1)...

Functions deploy had errors with the following functions:
	onChannelWrite(us-central1)
	onVideoWrite(us-central1)
i  functions: cleaning up build files...
Error: There was an error deploying functions:
- Error Failed to update function onVideoWrite in region us-central1
- Error Failed to update function onChannelWrite in region us-central1
```

**Comment by AhsinMehmood** [comment]
> > Artifact Registry API.
> 
> Artifact Registry API is enabled in my project , but still cant upload my functions
> 
> ```
> i  deploying functions
> ⚠  functions: package.json indicates an outdated version of firebase-functions.
> Please upgrade using npm install --save firebase-functions@latest in your functions directory.
> ⚠  functions: Please note that there will be breaking changes when you upgrade.
> i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
> i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
> i  functions: ensuring required API artifactregistry.googleapis.com is enabled...
> ✔  functions: required API artifactregistry.googleapis.com is enabled
> ✔  functions: required API cloudfunctions.googleapis.com is enabled
> ✔  functions: required API cloudbuild.googleapis.com is enabled
> i  functions: preparing functions directory for uploading...
> i  functions: packaged functions (58.77 KB) for uploading
> ✔  functions: functions folder uploaded successfully
> i  functions: updating Node.js 16 function onVideoWrite(us-central1)...
> i  functions: updating Node.js 16 function onChannelWrite(us-central1)...
> 
> Functions deploy had errors with the following functions:
> 	onChannelWrite(us-central1)
> 	onVideoWrite(us-central1)
> i  functions: cleaning up build files...
> Error: There was an error deploying functions:
> - Error Failed to update function onVideoWrite in region us-central1
> - Error Failed to update function onChannelWrite in region us-central1
> ```

Same issue
