### ISSUE TITLE
Missing traces in firebase functions using express, again

### ISSUE THREAD

**Issue by fgatti675** [firebase/firebase-functions#1625]
### Related issues

https://github.com/firebase/firebase-functions/issues/1439
This issue is the orginal thread that was marked as solved, when it isn't.
But please check it out to feel the growing frustration of many Google Cloud customers

### [REQUIRED] Version info

I am going to skip the template because it is not meaningful.

The Google Cloud logging traces are gone. They were there in v1 functions. We complained that they were not there in v2. They were added after months. Now they are gone again, for reasons only you know.

Everyone is complaining in a ticket that was closed and is getting no attention from Google.

Everytime I need to check a log I end up very frustrated. All I need is to see all the logs from a single execution of my v2 express function (which magically gets converted into a Google Cloud run instance).

I think you are failing at hiding complexity away, and you are causing a lot of frustration to your customers.

And the most anoying thing is that this goes on for YEARS now, and no one seems to care or answer.

All I need is that when I receive a request, I can see all logs of the same trace. WE USED TO HAVE THIS.
I have this instead, all logs are displayed with 0 tags, it is very hard to see what is going on in a single execution
<img width="556" alt="Screenshot 2024-10-08 at 16 33 11" src="https://github.com/user-attachments/assets/5a469274-ac94-4783-ae3e-b239d68109b0">

Is this thing not bothering you at Google? Are you not using your own products?
Please DO SOMETHING

**Comment by gbourne1** [comment]
Same issue

**Comment by gillycheesesteak** [comment]
I was having the issue, and adding LOG_EXECUTION_ID=false to my env file resolved it, although I'm not sure of the potential knock-on effects of that (based on this comment: https://github.com/firebase/firebase-functions/issues/1439#issuecomment-2391623377)

**Comment by adamxi** [comment]
> I was having the issue, and adding LOG_EXECUTION_ID=false to my env file resolved it, although I'm not sure of the potential knock-on effects of that (based on this comment: [#1439 (comment)](https://github.com/firebase/firebase-functions/issues/1439#issuecomment-2391623377))

Well nothing really, since according to the documentation of LOG_EXECUTION_ID, it's supposed to default to false anyway.

**Comment by fgatti675** [comment]
On month after this ticket was opened (for a paid service) and no one from Google has said a word

**Comment by larssn** [comment]
Attached is an example of "out of memory" errors in v1 and v2 respectively:

![image](https://github.com/user-attachments/assets/700f659c-a751-43ec-aebb-474bd2d36d6a)

It's pretty painful to debug v2 functions, of any kind. I'm considering downgrading to v1 again tbh.

**Comment by orestesgaolin** [comment]
I hope I might be able to help here, in my case v2 functions logging works, i.e. I can see levels, traces, labels and structured data. It's not showing automatically like in case of v1 functions but when filtering by `label.execution_id` I get all the logs from a given execution. Perhaps is it because I import v1 logger?

![screenshot_20241116_143105](https://github.com/user-attachments/assets/96138634-a8a0-4848-8b57-ac11bbdc7a35)

Some details that perhaps will help you:

```ts
import { logger } from "firebase-functions/v1";
import { onRequest, onCall } from "firebase-functions/v2/https";


export const functionName =
    onCall(
        {
            minInstances: minInstancesConfig,
            maxInstances: 200,
            memory: "512MiB",
            concurrency: 120,
            timeoutSeconds: 120,
        }, async (req) => {
            const data = req.data;
            try {
                logger.info("Log content", { userId: data.userId, headers: req.rawRequest.headers });

...
```

Versions:

```
"firebase-functions": "^6.1.0"
"@firebase/logger": "0.4.2"
```

**Comment by daniseijo** [comment]
Is there any news with this @CorieW?

**Comment by CorieW** [comment]
I was able to reproduce this. No labels are added to v2 logs.

**Comment by larssn** [comment]
Can we expect this to be looked at before 2026? It's a pretty crucial piece of functionality.

**Comment by jedney0901** [comment]
+1 on this please. This is critical for tracking requests

**Comment by cabljac** [comment]
Hi all, we're going to escalate this with the functions team.

From the SDK there might be some things we can emit in the structured log payload, but i'm not sure this would be a true fix, something might have to be changed in the runtime or cloud logging infra to inject labels on the entries.

**Comment by fgatti675** [comment]
We have implemented our own trace system, though injecting some context into google cloud logging.
Now we can see every log message relater to a http request.
Happy to write a blog article about it in case anyone is interested

**Comment by IPv6** [comment]
Still a problem... with deadline in March (v1 deprecation) this is really a showstopper for moving into v2 functions
Logs are much less usable now, without normal filtering as before...

**Comment by inlined** [comment]
Hi there, this just got escalated to my attention. I can try to reproduce some of this, but I'd like to know whether people are using console.log or the functions logger? To my recollection, we had previously only fixed this in the functions logger because there was some concern that patching console.log was an anti-pattern.

**Comment by inlined** [comment]
Sorry for the delay. Trying to reproduce this with the following test:

```
import { onRequest } from "firebase-functions/https";
import { logger } from "firebase-functions/logger";

export const traceTest = onRequest((req, res) => {
  console.log("Request headers are: ", JSON.stringify(req.headers, null, 2));
  logger.log("This is a message from the logger");
  res.send("OK");
});
```

In the Cloud Console I see both logs from console.log and from the Firebase logger have a consistent trace span ID (not guaranteed present) and execution ID. You can click on those IDs to filter with matching entries.

Have I missed the reproduction of the issue? Is this missing for particular event functions? Otherwise what is the broken feature?

<img width="420" height="238" alt="Image" src="https://github.com/user-attachments/assets/a872f874-a5d4-4037-b15c-ae29bd00ae9a" />

**Comment by cabljac** [comment]
@inlined  are you seeing logs in the logs explorer? I know that in extensions we're struggling to see logs in the log explorer, but they're visible in the cloud run function logs tab. Not sure if that's the same issue?

**Comment by cabljac** [comment]
I think there we are using the logger - `import {logger} from 'firebase-functions/v1';` for example

**Comment by cabljac** [comment]
> Perhaps is it because I import v1 logger?

Ah, perhaps this is the key here

**Comment by IPv6** [comment]
We are using "const logger = require("firebase-functions/logger");" and we indeed added execution_id as "summary field" - this works.

BUT with v1 function:
- previously there were no need to make "summary field" extra-setup (each time). Function names and execution ids were always visible as grey chips
- previously grey chips were also visible in Alerting logs panel (afaik there is no way to add "summary field" in alerting logs)
- previously the "Fields" side panel in log viewer (console.cloud.google.com) had quicks stats on what functions are present in the current query results. It was super easy to click on it and jump into subset, related to function. This is completely lost utility - summary fields are ignored in "Fields" side panel

**Comment by inlined** [comment]
There was once an original problem because of the execution model difference. Functions V1 only had one request per container so it was really easy to link that to an execution. But Functions V2 puts many requests in a container and only charges you while the container is active. This saves you money and reduces cold start, but made execution ID hard. But both the Firebase and Cloud teams implemented solutions for this. In my logs above, I was able to see execution ID on both console.log and logger.log. I think the big difference is that without the Firebase branded logs view, you have to click into the log statement to see it. Expand the log, look for executionId in the labels, and click to "Show matching entries" to restrict your view to only a single request in a single container.

WRT Extensions, they'd have to either set an environment variable to turn on Cloud's solution or use the functions logger library to turn on our solution and I expect many extensions do neither. But that is only for v2 functions in extensions. Are you sure you have those @cabljac? IIRC there's only one such extension.

**Comment by cabljac** [comment]
I will have to double check this, we ran into an issue where customers couldn't find logs on a v1 function, and generally across all extensions the query in log explorer that used to show function logs isnt working as expected. Tagging in @dackers86 here for context

**Comment by inlined** [comment]
@cabljac The logger is the same no matter where you import it from. It's just reexported in case people want all code to come from a specific namespace

@IPv6 Are we conflating V1 vs the change to the Firebase website to not have its own logging dashboard? The Cloud dashboard shows logs as the object structure they really are. You epxand one object and you'll see the execution and trace IDs. You can then click to filter to only matching logs. OTOH if you're writing a V1 extension, it's possible the extensions backend is not setting an environment variable it needs to in order to get some of these annotations.

**Comment by fgatti675** [comment]
Hey guys, original author of the post here. 
Since we were frustrated with the lack of traces, we have implemented a simple workaround in our backend (Node, express) that will add a trace per http request to every log, making it way easier to understand logs afterwards.
We have written a blog article exactly explaning how we did it. It has been running in production for months now:
https://firecms.co/blog/tracing_cloud_functions_v2/
Hope you find it helpful!

**Comment by adamxi** [comment]
So this problem is still going strong which is odd, because very early on in this thread a reference was posted to a detailed description of why the traces are missing as well as an actual fix.

I'll just leave this here:
https://github.com/firebase/firebase-functions/issues/1439#issuecomment-2391623377

**Comment by inlined** [comment]
The problem is "still going strong" because nobody is helping me reproduce. I showed screenshots that both trace and execution ID are working out of the box for me and need help understanding why this is supposed to be a problem. LOG_EXECUTION_ID is on for Firebase-deployed functions by default.

**Comment by cabljac** [comment]
We'll jump back on this @inlined, i'll catch up with @IzaakGough on this first thing tomorrow

**Comment by cabljac** [comment]
So after an investigation today, our reproductions align with what @inlined is reporting.

With extensions I think we may be just seeing some bug or quirk with the log explorer. The logs don't appear every time the query runs, whereas they used to be consistent - now the initial opening of the log explorer doesn't seem to run the query.

We'll try an extension that uses a v2 function (there are 2 of these)

**Comment by IzaakGough** [comment]
We have now verified that logs exist for both v1 and v2 extensions. It seems that function logs not sometimes not appearing has something to do with the log explorer itself.

**Comment by inlined** [comment]
Nobody has responded that this bug is reproducing for them in several months. Closing as not able to reproduce
