### ISSUE TITLE
Node 10 callable function returning unauthenticated

### ISSUE THREAD

**Issue by doowb** [firebase/firebase-functions#432]
### [REQUIRED] Version info

**node:**

`v10.15.2`

**firebase-functions:**
`2.3.0`

**firebase-tools:**

`6.8.0`

**firebase-admin:**
`7.3.0`

### [REQUIRED] Test case

Create a callable function:

```js
exports.hello = functions.https.onCall(async (data, context) => {
  return { message: 'Hello World' };
});
```

In client side javascript, call the function after the user has logged in:

```js
firebase.auth().onAuthStateChanged(user => {
  if (user) {
    firebase.functions()
      .httpsCallable('hello')()
      .then(result => {
        console.log(result);
      })
      .catch(err => {
        console.error(err);
      });
  }
});
```

### [REQUIRED] Steps to reproduce

Deploy the function using the `node 10` engine configured in the functions `package.json`.
Deploy the html with the client side code for authenticating and calling the function to firebase hosting.
Navigate to the page hosted on firebase and login.

### [REQUIRED] Expected behavior

See the response from the callable function output in the browser console.
This is when deployed using `node 8`:

```js
{ data: { message: 'Hello World' } }
```

### [REQUIRED] Actual behavior

`Unauthenticated` error response from calling the function. This does not happen when the function is deployed using `node 8` as the engine.

<summary>
<details>

```
Navigated to https://boilerplate-user-management.firebaseapp.com/
hello:1 POST https://us-central1-boilerplate-user-management.cloudfunctions.net/hello 401
index.js:26 Error: Unauthenticated
    at new i (error.ts:65)
    at error.ts:172
    at e.<anonymous> (service.ts:215)
    at tslib.es6.js:97
    at Object.next (tslib.es6.js:78)
    at n (tslib.es6.js:68)
(anonymous) @ index.js:26
Promise.catch (async)
(anonymous) @ index.js:25
(anonymous) @ subscribe.ts:104
(anonymous) @ subscribe.ts:225
Promise.then (async)
t.sendOne @ subscribe.ts:222
t.forEachObserver @ subscribe.ts:213
t.next @ subscribe.ts:103
n @ auth.js:1281
(anonymous) @ auth.js:1807
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:503
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:503
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:436
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:426
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
(anonymous) @ rpchandler.js:789
(anonymous) @ rpchandler.js:520
Ce @ eventtarget.js:285
_e.dispatchEvent @ eventtarget.js:383
Wo @ xhrio.js:872
t.yc @ xhrio.js:818
t.Jb @ xhrio.js:802
XMLHttpRequest.send (async)
Ko @ xhrio.js:632
da.m @ rpchandler.js:549
Ta @ rpchandler.js:455
(anonymous) @ rpchandler.js:777
pt @ promise.js:171
(anonymous) @ rpchandler.js:772
(anonymous) @ rpchandler.js:758
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:503
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:503
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:503
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:526
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:503
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:443
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:397
IndexedDB (async)
(anonymous) @ indexeddb.js:426
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
(anonymous) @ promise.js:175
t.onsuccess @ indexeddb.js:322
IndexedDB (async)
(anonymous) @ indexeddb.js:282
pt @ promise.js:171
xs @ indexeddb.js:283
Ms @ indexeddb.js:339
set @ indexeddb.js:421
(anonymous) @ indexeddb.js:251
e.g @ promise.js:832
Ct @ promise.js:1171
Rt @ promise.js:1145
t.Yb @ promise.js:1116
dt @ run.js:132
Promise.then (async)
rt @ run.js:63
ht @ run.js:42
_t @ promise.js:1034
Nt @ promise.js:927
It @ promise.js:353
Ws @ hybridindexeddb.js:57
ou @ factory.js:118
au @ authstorage.js:229
Kc @ storageusermanager.js:89
Jc @ auth.js:121
qh.INTERNAL.extendNamespace.User @ exports_auth.js:634
t._getService @ firebaseApp.ts:161
An.<computed> @ firebaseNamespace.ts:226
(anonymous) @ exports_auth.js:696
(anonymous) @ firebaseNamespace.ts:250
p @ firebaseNamespace.ts:242
initializeApp @ firebaseNamespace.ts:158
(anonymous) @ init.js:2
```

</details>
</summary>

### Were you able to successfully deploy your functions?

Yes, they successfully deployed, there are no error messages when deploying.

**Comment by thechenky** [comment]
Hi @doowb would you be able to provide more of the code so that I can try to reproduce? Specifically the client side code and your hosting assets.

**Comment by thechenky** [comment]
This seems like it touches a lot of the Firebase product pieces and something is happening in a call between two systems. I feel like this would be a more involved case that is better solved by filing a [support ticket](https://firebase.google.com/support) (also the advantages there are that you can fully share your code without it being visible publicly).

**Comment by doowb** [comment]
@thechenky thanks for responding so quickly. This isn't a stopper for me right now since the functions work when deployed with `node 8`. I'll try to create a minimal case to post here and open a ticket if it becomes an issue in my main code.

**Comment by thechenky** [comment]
@doowb thanks! Would be great to see a minimal case so that I can try to reproduce. Curious, do you have other Node 10 functions? And do they work alone in isolation?

**Comment by doowb** [comment]
The function that had the issue was using the admin sdk so I created the `hello` function to see if the issue was with the function or with the admin sdk. This project doesn't have any other functions yet. It will have auth triggers and firestore triggers, but I haven't tested those yet.

Also, I do realize that `node 10` is still in `beta` for `firebase-functions` so I understand there might be some issues.

**Comment by thechenky** [comment]
Are you using a VPC of any kind? This is puzzling because it sounds like a permissions issue where the client cannot call the HTTP function - but this should be independent of the runtime. Are you able to call the function directly (by hitting the URL yourself, not in the client)?

**Comment by doowb** [comment]
I haven't had a chance to try that yet. Also, I just started using callable functions and I wasn't aware that I could call it through the URL directly.

**Comment by LanderBeeuwsaert** [comment]
Hey, jumping in here. I have the same issue. It's ok if I use node 8 as engine (in package.json)
I use callables:
functions().httpsCallable("xyz")(params);

**Comment by mbleigh** [comment]
I have a couple ideas of places to look. I think it might have to do with
the environment variable differences between Node 8 and 10 runtimes in
Cloud Functions.

Hopefully we can dig further soon.

*From: *LanderBeeuwsaert <notifications@github.com>
*Date: *Fri, May 3, 2019, 11:20 PM
*To: *firebase/firebase-functions
*Cc: *Subscribed

Hey, jumping in here. I have the same issue. It's ok if I use node 8 as

**Comment by thechenky** [comment]
Thanks everyone for your feedback - this does indeed look like a bug on our side specific to Node 10 functions. We are working on a fix. Please see https://github.com/firebase/firebase-functions/issues/433 for more context. Thanks for your patience!

**Comment by thechenky** [comment]
Quick update: this looks like it might be a bug in the functions backend (see #434 (comment)). We are working with the relevant teams to resolve these issues. Thanks for everyone's patience!

**Comment by doowb** [comment]
@thechenky Thanks for the update!

**Comment by thechenky** [comment]
@doowb I'm curious to see this value, can you add a `console.log(process.env.GCLOUD_PROJECT` in both your function and your client? Is it empty?

Regarding `FIREBASE_CONFIG` and `functions.config()` values being not set, we've put in a fix: https://github.com/firebase/firebase-functions/issues/433#issuecomment-491053925

**Comment by enbyted** [comment]
I'm new to firebase and this took me a few hours to find this bug report.

I discovered an interesting property - in node 10 engine for callable function when 'Authorization' header is missing the function is executed fine, but when it's present (either valid or invalid) the function is never executed and firebase returns `{"error":{"status":"UNAUTHENTICATED","message":"Unauthenticated"}}`.

**Comment by doowb** [comment]
Hi @thechenky, sorry for the delay in getting back to you. I've seen that you've been deploying new versions that might resolve this, but I don't think it's resolved yet.

I created a simple [demo here](https://github.com/doowb/firebase-callable-functions-demo). When I deployed the function as `node 8`, it worked fine. When I deploy it as `node 10`, I see in the logs:

```
Warning, FIREBASE_CONFIG environment variable is missing. Initializing firebase-admin will fail
```

Then when I execute the function from the client side, I get this error in the browser console:
![image](https://user-images.githubusercontent.com/995160/57951465-20232300-78b8-11e9-8e87-1a26b86af86f.png)

And the logs show the function being invoked twice... first with a 204, then a 401:
![image](https://user-images.githubusercontent.com/995160/57951566-67a9af00-78b8-11e9-8e9f-03ab591f5b1a.png)

The billing warning is because I didn't turn on billing for this demo project but I received the same errors on a project with billing turned on.

I hope this helps.

**Comment by thechenky** [comment]
@doowb @enbyted The fix has been rolled out to production. Please let me know if you're still seeing issues.

**Comment by loicmarie** [comment]
Is the fix working with the firebase functions emulator ? Cause I still have the same error with the same versions
`ERROR Error: Unauthenticated ...`

**Comment by thechenky** [comment]
@loicmarie if you're having an issue with the emulator please file it in the Firebase CLI repo: https://github.com/firebase/firebase-tools. Make sure your CLI is upgraded to latest, as well.

**Comment by Twinsens** [comment]
Any update for this issue? I'm still get 
**System.AggregateException: One or more errors occurred. ---> Firebase.Functions.FunctionsException: Unauthenticated**

It was begin when I upgrade my firebase_unity_sdk 6.0.0 to 6.1.1. 

On server side ;

 "firebase-admin": "^8.1.0",
 "firebase-functions": "^2.3.1",
 "firebase-functions-helper": "^0.7.1"

Unity side : 
firebase_unity_sdk 6.1.1

**Comment by LanderBeeuwsaert** [comment]
I just deployed and tested with:
  "dependencies": {
    "firebase": "^6.2.0",
    "firebase-admin": "~8.1.0",
    "firebase-functions": "^3.0.1",
    "firebase-tools": "^7.0.0",
  },

and   "engines": {
    "node": "10"
  }

and everything worked just fine

**Comment by pjc0247** [comment]
@thechenky where can i get older version of sdk? 
I think this issue still exists.

**Comment by thechenky** [comment]
@pjc0247 please open a new issue if you are running into problems. You can get an older version of firebase functions by installing a specific version with npm: `npm install firebase-functions@2.3.1`

**Comment by pjc0247** [comment]
@thechenky 
as Twinsens said
`It was begin when I upgrade my firebase_unity_sdk 6.0.0 to 6.1.1.`

So, I want to test with older version of Unity SDK first, and if error still exists I'll open a new issue.

I know this is a functions repo, but if you know where can I find older version of Unity SDK, please let me know. because [firebase unity repo](https://github.com/firebase/Firebase-Unity) is dead.
