### ISSUE TITLE
Unable to import https.HttpsError class

### ISSUE THREAD

**Issue by the-jackalope** [firebase/firebase-functions#942]
### Related issues

Could not find this specific issue linked.

### [REQUIRED] Version info

**node:**
`v14.17.1`

**firebase-functions:**
`v3.15.1`

**firebase-tools:**
`v9.16.1`

**firebase-admin:**
`v9.11.0`

**typescript**
`v3.8.3`

### [REQUIRED] Test case
```typescript
// index.ts

import * as functions from 'firebase-functions';

function example() {
  throw new functions.https.HttpsError('example-reason', 'example-message');
}
```
The above example will fail 

### [REQUIRED] Steps to reproduce

Attempt to build/run the above example using standard `tsconfig.json` from the Firebase Functions example repository.

### [REQUIRED] Expected behavior

The above code will compile, instantiate an `HttpsError` class, and throw it.

### [REQUIRED] Actual behavior

Fails with the following message:
```
src/helpers/common.ts:7:31 - error TS2339: Property 'HttpsError' does not exist on type 'typeof import("/Users/path/to/project/functions/node_modules/firebase-functions/lib/v1/providers/https")'.
```
It appears that only the type declaration is exported, and not the class itself.

Attempting to import the `HttpsError` class directly, e.g.:
```typescript
import { HttpsError } from 'firebase-functions/lib/common/providers/https';
```
Causes the following error during the `parsing your function triggers` stage of deployment:
```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/common/providers/https' is not defined by "exports" in /home/runner/work/firebase-fns/firebase-fns/functions/node_modules/firebase-functions/package.json
```

### Were you able to successfully deploy your functions?

Not able to successfully deploy: see above.

**Comment by kchoao** [comment]
I got the same issue here when I tried to run `firebase serve`.
`⚠  functions: Cannot find module '/Users/user/Desktop/workspace/express-firebase/functions/node_modules/firebase-functions/lib/providers/https'
Require stack:`
`Require stack:
- /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js
⚠  Your function was killed because it raised an unhandled error.`

**Comment by studds** [comment]
FYI this broke our production app when we redeployed a minor change. Not impressed at introducing this breaking change in a minor / patch version.

**Comment by Joebayld** [comment]
I agree with @studds. My app also broke with this update. This is not the first time an update broke basic functionality.

It seems like updating is a very dangerous operation with Firebase lately. Definitely going to be holding back longer on any updates in the future. Please improve the testing @firebase!

**Comment by fingerartur** [comment]
Firebase why you do this to me? :crying_cat_face:

**Comment by siarheidudko** [comment]
I get the same problem in production.

**Comment by swftvsn** [comment]
Problem for us too.

**Comment by Joebayld** [comment]
To anyone still with the issue - make sure you’re on the latest CLI v9.16.2. I was on v9.16.0 before and after upgrading it seems to have fixed the issue. 

Still not great that this was a breaking update, but seems to be a fix.

**Comment by svenjacobs** [comment]
> To anyone still with the issue - make sure you’re on the latest CLI v9.16.2. I was on v9.16.0 before and after upgrading it seems to have fixed the issue.
> 
> Still not great that this was a breaking update, but seems to be a fix.

Are you sure? Why should CLI interfere with TypeScript compilation?

**Comment by Joebayld** [comment]
I had errors thrown when launching the emulator. Someone else also posted the error earlier: 

`Require stack: - /usr/local/lib/node_modules/firebase-tools/lib/emulator/functionsEmulatorRuntime.js ⚠ Your function was killed because it raised an unhandled error.`

Could be two different issues going on, but my guess is something weird with the emulator runtime?

**Comment by opudalo** [comment]
### Changing directory structure in a minor patch be like
![image](https://user-images.githubusercontent.com/775750/129176799-a948c3a7-ee02-43dd-ac3e-a7f94eaecc0b.png)

To whom it may concern the fix that worked for me:

```javascript
// before
import { UserRecord } from 'firebase-functions/lib/providers/auth'

// after
import { UserRecord } from 'firebase-functions/lib/v1/providers/auth'
```

**Comment by fobo66** [comment]
I had this issue with Realtime Database functions, I also had unresolved error with an import, but I've managed to fix it by importing from the correct location:

```typescript
import { database } from 'firebase-functions/v1';
```

However, it didn't help much, because there was another error:

```

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in /Users/fobo66/algolia-firebase-functions/node_modules/firebase-functions/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:335:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:560:3)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/fobo66/algolia-firebase-functions/node_modules/firebase-functions-test/lib/providers/firestore.js:26:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.replacementCompile (/Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at /Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:64:4
    at require.extensions.<computed> (/Users/fobo66/algolia-firebase-functions/node_modules/ts-node/src/index.ts:1301:43)
    at Object.<anonymous> (/Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.<anonymous> (/Users/fobo66/algolia-firebase-functions/node_modules/firebase-functions-test/lib/features.js:8:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.replacementCompile (/Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:60:13)
    at Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at /Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:64:4
    at require.extensions.<computed> (/Users/fobo66/algolia-firebase-functions/node_modules/ts-node/src/index.ts:1301:43)
    at Object.<anonymous> (/Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at module.exports (/Users/fobo66/algolia-firebase-functions/node_modules/firebase-functions-test/lib/index.js:30:20)
    at Object.<anonymous> (/Users/fobo66/algolia-firebase-functions/test/test.ts:24:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Module.replacementCompile (/Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:60:13)
    at Module.m._compile (/Users/fobo66/algolia-firebase-functions/node_modules/ts-node/src/index.ts:1311:23)
    at module.exports (/Users/fobo66/algolia-firebase-functions/node_modules/default-require-extensions/js.js:7:9)
    at /Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:64:4
    at require.extensions.<computed> (/Users/fobo66/algolia-firebase-functions/node_modules/ts-node/src/index.ts:1314:12)
    at Object.<anonymous> (/Users/fobo66/algolia-firebase-functions/node_modules/append-transform/index.js:64:4)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:94:18)
    at Object.exports.requireOrImport (/Users/fobo66/algolia-firebase-functions/node_modules/mocha/lib/esm-utils.js:56:20)
    at async Object.exports.loadFilesAsync (/Users/fobo66/algolia-firebase-functions/node_modules/mocha/lib/esm-utils.js:88:20)
    at async singleRun (/Users/fobo66/algolia-firebase-functions/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/Users/fobo66/algolia-firebase-functions/node_modules/mocha/lib/cli/run.js:366:5)
```

So, it feels like there were some changes in the folders structure that were not properly handled in package.json

**Comment by theochampion** [comment]
@nilsreichardt Still getting the problem when downgrading to `3.14.1` :/

**Comment by nilsreichardt** [comment]
I forget to add that with `3.14.1` I'm able to use the old imports, like:
```ts
import { HttpsError } from "firebase-functions/lib/providers/https";
```

or

```ts
import * as functions from "firebase-functions";
new functions.https.HttpsError();
```

And this is working for me. So for now I'm using the old imports until this issue open.

**Comment by pmoralesp** [comment]
I had same problem. Upgrading `firebase-tools` from 8.16.2 to latest 9.16.2 solved it.

`npm install -g firebase-tools`

**Comment by rfb** [comment]
If I'm reading this correctly, HttpsError is exported from `firebase-functions/lib/common/providers/https` now.

`import { HttpsError } from 'firebase-functions/lib/common/providers/https';`

**Comment by mbleigh** [comment]
Hi folks, sorry to see all the trouble the new releases of `firebase-functions` and `firebase-tools` are causing. We did change the directory structure of `firebase-functions` and there are clearly gaps between our testing and real-world usage.

We are working to quickly bring out a new release that fixes the issues you're experiencing, but until then we recommend reverting to `firebase-functions@3.14.1` and `firebase-tools@9.16.0`.

**Comment by drcampbell** [comment]
I tried reverting to version 3.14.1 but I can't deploy my functions to the firebase.

**Comment by mbleigh** [comment]
We have released new versions of both libraries that should address this. Please try `firebase-functions@3.15.2` and `firebase-tools@9.16.3` and let me know if you are still experiencing issues.

**Comment by diver-sity** [comment]
The team I'm with are also experiencing the same issue. I could not deploy even with `firebase-functions@3.14.1`. The failure was with the Firebase environment apparently:
```
✔  functions: Finished running predeploy script.
⚠  functions: package.json indicates an outdated version of firebase-functions.
Please upgrade using npm install --save firebase-functions@latest in your functions directory.
 i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
 i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
 ✔  functions: required API cloudfunctions.googleapis.com is enabled
 ✔  functions: required API cloudbuild.googleapis.com is enabled
 i  functions: Loaded environment variables from .
 
 Error: Missing bucket name. If you are unit testing, please provide a bucket name through `functions.storage.bucket(bucketName)`, or set process.env.FIREBASE_CONFIG.
```
We did not change the setting related to the deployment environment variable bucket so that line
` i  functions: Loaded environment variables from .`
did not look right. Comparing the deployment log entries with previous days, that line is also an extra. 

What happened, the Firebase team? Both the node.js package and the deployment environment failed?

**Comment by davidbielik** [comment]
> We have released new versions of both libraries that should address this. Please try `firebase-functions@3.15.2` and `firebase-tools@9.16.3` and let me know if you are still experiencing issues.

Hi, I can still reproduce this on `3.15.2`. 

Downgrading back to `^3.14.1` works (had to undo changes to lock files).

**Comment by johnnyoshika** [comment]
I think this is related, and while my TypeScript compiles and deploys, I get this exception in production:

```
2021-08-12T20:35:15.131Z test 3co9g97v0m98 Unhandled error TypeError: functions.https.HttpsError is not a constructor at someFunction (/workspace/lib/callables/test.js:42:15) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async /workspace/lib/callables/test.js:103:22 at async /workspace/node_modules/firebase-functions/lib/common/providers/https.js:322:26
Unhandled error TypeError: functions.https.HttpsError is not a constructor at test(/workspace/lib/callables/test.js:42:15) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async /workspace/lib/callables/test.js:103:22 at async /workspace/node_modules/firebase-functions/lib/common/providers/https.js:322:26
```

I provided detailed information about this on StackOverflow: https://stackoverflow.com/q/68763955/188740

This was fixed by downgrading to `firebase-functions@3.14.1`

**Comment by leon** [comment]
Also having troubles with firebase-functions 3.15.2

there seems to be changes where a v1 and v2 folder is introduced...

```
Package subpath './lib/common/providers/https' is not defined by "exports"
```

When importing
```
import { HttpsError } from 'firebase-functions/lib/providers/https'
```

What will be the best practices going forward.
are you going to make it possible for us to import from 'firebase/v2'?

**Comment by efstathiosntonas** [comment]
in this lines https://github.com/firebase/firebase-functions/blob/1d80b5f34bccb5c8cf678f0f50f4945c7e265269/package.json#L28
https://github.com/firebase/firebase-functions/blob/1d80b5f34bccb5c8cf678f0f50f4945c7e265269/package.json#L29



it asks for v1 folder but there is only v2 folder 

![Screenshot 2021-08-13 at 1 14 15 PM](https://user-images.githubusercontent.com/717975/129342347-9ad8df28-4fd2-4a88-9384-5f3e1028b75e.png)

**Comment by mikquinlan** [comment]
Same issue here, but with `pubsub` package trying to import `Message` class for pubSub functions in Typescript.

`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/providers/pubsub' is not defined by "exports" `

Fixed by downgrading to 3.14.1.

**Comment by drcampbell** [comment]
I was able to deploy functions again after upgrading my node engine from node version 10 to 14.  Is Version 10 now deprecated with the latest builds?

**Comment by inlined** [comment]
@mikquinlan, @efstathiosntonas, & @leon  We were of the stance that we could/should break imports of every lib/ except for lib/logger and lib/logger/compat because they were never documented and thus not part of a public API surface. #948 is going to fix this for you _for now_ but we're definitely ripping out all `/lib` paths in the next major release. We've provided v2-like options where you can now import `v1/https` instead of `lib/providers/https`, but I'm not even sure we really want to keep those. The v1 APIs weren't designed to be deep-imported unlike v2. Speaking of which, v2 is coming but isn't ready yet. If you want to provide feedback, make sure you're in our alpha group. I'm particularly interested in hearing from users like you who want to do deep-imports.

@drcampbell Node 10 is still supported for now, though the writing is on the wall. I'd recommend upgrading to a version of Node that is still supported by the community & getting security patches.

@johnnyoshika Looking into your error. We'll get it fixed.

**Comment by davidbielik** [comment]
Hi @inlined 

just in case it's unclear, this broke for typescript projects using the [widely documented examples](https://github.com/firebase/quickstart-js/blob/bf3d61691cc9d75cd15a3f3d783ed985721fe2c7/functions/functions/index.js#L64-L75) of throwing errors.

I don't import those as others are referencing.

```
throw new functions.https.HttpsError('invalid-argument', 'The function must be called with ' +
        'one arguments "text" containing the message text to add.');
```

**Comment by inlined** [comment]
Yes, `throw new functions.https.HttpsError('invalid-argument', 'foo')` is absolutely defined behavior that was accidentally broken. Fix is upcoming. The intentional break that we're temporarily backtracking on is `import { HttpsError } from 'firebase-functions/lib/providers/https'`

**Comment by mikquinlan** [comment]
@inlined Thanks for the info. The error I reported happens when I migrate to v2 of Message.

**Comment by inlined** [comment]
@all firebase-functions 3.15.3 should address the issues in this thread, so I'll close it.

@mikquinlan The v2 SDK is definitely not ready for public use. Stick with v1 for now unless you join the alpha testers group and get instructions for using the v2 SDK.

**Comment by mikquinlan** [comment]
@inlined Thanks, I'm not using it based on your advice.

This update does fix the errors, above, however, it does not work with 0.3.1 of firebase-functions-test

When executing 

```
import * as firebaseFunctionsTest from 'firebase-functions-test';
export const test = firebaseFunctionsTest({});
```

the following error is thrown:

```
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in /Users/mquinlan/work/projects/pretzel/delivery/functions/node_modules/firebase-functions/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:285:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:508:3)
    at resolveExports (internal/modules/cjs/loader.js:424:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:464:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:802:27)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mquinlan/work/projects/pretzel/delivery/functions/node_modules/firebase-functions-test/lib/providers/firestore.js:26:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:702:16)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/mquinlan/work/projects/pretzel/delivery/functions/node_modules/firebase-functions-test/lib/features.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:702:16)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at module.exports (/Users/mquinlan/work/projects/pretzel/delivery/functions/node_modules/firebase-functions-test/lib/index.js:30:20)
```

**Comment by siarheidudko** [comment]
I have the same problem with export.
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/encoder' is not defined by "exports" in /.../firebase/functions/node_modules/firebase-functions/package.json`

**Comment by inlined** [comment]
We'll fix it today with a new version of firebase-functions-test

**Comment by inlined** [comment]
firebase-functions-test@0.3.2 should fix the issue.

**Comment by siarheidudko** [comment]
I'm still getting a problem with the tests. `Error: Wrap can only be called on functions written with the firebase-functions SDK.`

**Comment by dsl101** [comment]
I was still getting this with the current versions (3.15.7 and 9.20.0), and it turned out it was because I was using regionalised versions of functions, and this apparently doesn't support `HttpsError`:
```js
const functions = require('firebase-functions').region(myRegion)

exports = module.exports = functions.https.onCall(async (data, context) => {
  throw new functions.https.HttpsError('permission-denied', 'Not for you')  // This results in Unhandled error TypeError: HttpsError is not a constructor
})
```

Note this did work in versions prior to the update mentioned in this thread. Now, using this works fine:
```js
let functions = require('firebase-functions')
const HttpsError = functions.https.HttpsError
functions = functions.region(myRegion)

exports = module.exports = functions.https.onCall(async (data, context) => {
  throw new HttpsError('permission-denied', 'Not for you')  // Works fine now
})

```

Even though the `region()` method returns a `FunctionBuilder`, it doesn't appear to include all the required properties to access the error constructor.

**Comment by johnnyoshika** [comment]
@dsl101 well that's frustrating. I will encounter the same problem once I upgrade `firebase-functions`, as I use regionalized functions as well. I'm still on `firebase-functions@3.14.1`. I had to downgrade because of the problem outlined in this issue. The issue's been fixed, but I'm now gun shy.

**Comment by johnnyoshika** [comment]
@inlined good point

**Comment by AathifMahir** [comment]
Still having this issue with v4.0.2

**Comment by josephmangmang** [comment]
Use
`import { HttpsError } from "firebase-functions/lib/common/providers/https";`

**Comment by MaxGenash** [comment]
I had a similar issue "Unhandled error Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/v1/providers/https' is not defined by \"exports\" in ./functions/node_modules/firebase-functions/package.json" in `firebase-functions@4.1.1`. Figured out that in package.json of firebase-functions there is defined a list of exports mappings, so the fix was to change an import from `import {HttpsError} from 'firebase-functions/lib/v1/providers/https';` to `import {HttpsError} from 'firebase-functions/v1/https';`

**Comment by edriang** [comment]
For me, the correct way of importing to avoid build errors was to import `import { https } from 'firebase-functions/v1'` and then use it with `https.HttpsError`, e.g.:
```
throw new https.HttpsError('failed-precondition', 'User should have an account');
```

**Comment by atsushi-macchang** [comment]
``` 
import * as functions from 'firebase-functions'; 

const { HttpsError } = functions.https; 
``` 
How about doing a "destructuring assignment"?
